### ISSUE TITLE
Windows client can't connect to Ubuntu 16.04 server

### ISSUE THREAD

**Issue by AHPyXA** [undermind/ssvnc-setup#1]
Server-side log

> 21/05/2017 18:15:54 SSL: ssl_init[27157]: 0/1 initialization timeout: 20 secs.
> 21/05/2017 18:15:54 SSL: ssl_helper[27157]: SSL_accept() *FATAL: -1 SSL FAILED
> 21/05/2017 18:15:54 SSL: error:1408A10B:**SSL routines:ssl3_get_client_hello:wrong version number**
> 21/05/2017 18:15:54 SSL: ssl_helper[27157]: Proto: nosession
> 21/05/2017 18:15:54 SSL: ssl_helper[27157]: exit case 2 (ssl_init failed)
> 21/05/2017 18:15:54 SSL: accept_openssl: cookie from ssl_helper[27157] FAILED. 0

SSLv3 was [disabled ](https://askubuntu.com/questions/774760/openssl-s-client-connect-gmail-com443-ssl3-not-working/780025#780025)in ubuntu 16.04

We needs add options in stunnel.conf on client-side:
```
sslVersion = all
options = NO_SSLv2
options = NO_SSLv3
```

**Comment by AHPyXA** [comment]
https://github.com/undermind/ssvnc-setup/pull/2

**Comment by undermind** [comment]
Pull request accepted. I'll try to build project late night and check it.
Спасибо большое!
